// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzbHVyh_4ZonuM7bcVXToIHx9V11IQKTw',
    appId: '1:1080544096777:web:c73128e05b4159a9553ed8',
    messagingSenderId: '1080544096777',
    projectId: 'gkfc-tracking-car-multi',
    authDomain: 'gkfc-tracking-car-multi.firebaseapp.com',
    storageBucket: 'gkfc-tracking-car-multi.firebasestorage.app',
    measurementId: 'G-C02LZPBYMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFqgu9ElmKoGMR61q1c-WtJgfg9aI-w84',
    appId: '1:1080544096777:android:9071fd4b8fa0a88f553ed8',
    messagingSenderId: '1080544096777',
    projectId: 'gkfc-tracking-car-multi',
    storageBucket: 'gkfc-tracking-car-multi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZXsCwluuil1iBV2IG18oIbkcE9crFKl0',
    appId: '1:1080544096777:ios:c964a2a2ec086405553ed8',
    messagingSenderId: '1080544096777',
    projectId: 'gkfc-tracking-car-multi',
    storageBucket: 'gkfc-tracking-car-multi.firebasestorage.app',
    iosBundleId: 'com.example.gkfcTrackingCarMulti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzbHVyh_4ZonuM7bcVXToIHx9V11IQKTw',
    appId: '1:1080544096777:web:ec256e1f7530215e553ed8',
    messagingSenderId: '1080544096777',
    projectId: 'gkfc-tracking-car-multi',
    authDomain: 'gkfc-tracking-car-multi.firebaseapp.com',
    storageBucket: 'gkfc-tracking-car-multi.firebasestorage.app',
    measurementId: 'G-WN7RLFVGFQ',
  );
}
